development:
  bin_path: "/usr/local/sphinx/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  
test:
  bin_path: "/usr/local/sphinx/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer

production:  
  bin_path: "/opt/bitnami/sphinx/bin"
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  
